import { randomUUID } from 'crypto'
import { app, BrowserWindow, shell } from 'electron'
import { access, mkdir, readFile, readdir, rm, stat, writeFile } from 'fs/promises'
import { join } from 'path'
import { IPC } from '../../../shared/ipc'
import {
  HOST_EDITABLE_PROPERTIES,
  type CreateHostServerDto,
  type HostDownloadProgressDto,
  type HostEditablePropertyKey,
  type HostMutationDto,
  type HostPropertiesDto,
  type HostServerMeta,
  type HostServerView,
  type HostWorldEntryDto,
  type UpdateHostServerDto
} from '../../../shared/host-types'
import { downloadService } from '../DownloadService'
import { resolveJavaPath } from '../../minecraft/JavaService'
import { settingsStore } from '../../storage/SettingsStore'
import { pluginInstallService } from './PluginInstallService'
import { serverProcessManager } from './ServerProcessManager'
import { serverSoftwareCatalog } from './ServerSoftwareCatalog'

const META_FILE = 'prime-host.json'
const JAR_NAME = 'server.jar'

function hostRoot(): string {
  return join(app.getPath('userData'), 'host-servers')
}

function serverDir(id: string): string {
  return join(hostRoot(), id)
}

function metaPath(id: string): string {
  return join(serverDir(id), META_FILE)
}

function propertiesPath(id: string): string {
  return join(serverDir(id), 'server.properties')
}

function eulaPath(id: string): string {
  return join(serverDir(id), 'eula.txt')
}

function jarPath(id: string): string {
  return join(serverDir(id), JAR_NAME)
}

async function pathExists(p: string): Promise<boolean> {
  try {
    await access(p)
    return true
  } catch {
    return false
  }
}

function validateName(name: string): string | null {
  const trimmed = name.trim()
  if (trimmed.length < 1 || trimmed.length > 48) {
    return 'Name must be 1–48 characters.'
  }
  return null
}

function validatePort(port: number): string | null {
  if (!Number.isInteger(port) || port < 1 || port > 65535) {
    return 'Port must be an integer between 1 and 65535.'
  }
  return null
}

function validateRam(ramMb: number): string | null {
  if (!Number.isFinite(ramMb) || ramMb < 512 || ramMb > 65536) {
    return 'RAM must be between 512 and 65536 MB.'
  }
  return null
}

function parseProperties(raw: string): Record<string, string> {
  const out: Record<string, string> = {}
  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue
    const eq = trimmed.indexOf('=')
    if (eq < 0) continue
    out[trimmed.slice(0, eq)] = trimmed.slice(eq + 1)
  }
  return out
}

function serializeProperties(map: Record<string, string>): string {
  const lines = [
    '#Minecraft server properties',
    `#Generated by Prime Launcher ${new Date().toISOString()}`
  ]
  for (const key of Object.keys(map).sort()) {
    lines.push(`${key}=${map[key]}`)
  }
  return `${lines.join('\n')}\n`
}

function defaultProperties(port: number, name: string): Record<string, string> {
  return {
    'server-port': String(port),
    motd: name,
    'max-players': '20',
    'online-mode': 'true',
    'view-distance': '10',
    'simulation-distance': '10',
    difficulty: 'easy',
    gamemode: 'survival',
    'white-list': 'false',
    'enforce-whitelist': 'false',
    pvp: 'true',
    'spawn-protection': '16',
    'max-world-size': '29999984',
    'level-name': 'world',
    'level-type': 'minecraft\\:normal',
    'allow-nether': 'true',
    'enable-command-block': 'false',
    'spawn-monsters': 'true',
    'spawn-animals': 'true',
    'spawn-npcs': 'true',
    'force-gamemode': 'false',
    hardcore: 'false'
  }
}

function broadcastDownload(payload: HostDownloadProgressDto): void {
  for (const win of BrowserWindow.getAllWindows()) {
    win.webContents.send(IPC.HOST_DOWNLOAD_PROGRESS, payload)
  }
}

export class HostServerService {
  async ensureRoot(): Promise<void> {
    await mkdir(hostRoot(), { recursive: true })
  }

  async list(): Promise<HostServerView[]> {
    await this.ensureRoot()
    const entries = await readdir(hostRoot(), { withFileTypes: true })
    const servers: HostServerView[] = []
    for (const entry of entries) {
      if (!entry.isDirectory()) continue
      try {
        servers.push(await this.toView(await this.readMeta(entry.name)))
      } catch {
        // skip corrupt folders
      }
    }
    return servers.sort((a, b) => b.updatedAt.localeCompare(a.updatedAt))
  }

  async get(id: string): Promise<HostServerView | null> {
    try {
      return await this.toView(await this.readMeta(id))
    } catch {
      return null
    }
  }

  async create(input: CreateHostServerDto): Promise<HostMutationDto> {
    const nameErr = validateName(input.name)
    if (nameErr) return { ok: false, error: nameErr }
    const portErr = validatePort(input.port)
    if (portErr) return { ok: false, error: portErr }
    const ramErr = validateRam(input.ramMb)
    if (ramErr) return { ok: false, error: ramErr }

    let build
    try {
      build = await serverSoftwareCatalog.resolveBuild(input.software, input.mcVersion, input.build)
    } catch (err) {
      return { ok: false, error: err instanceof Error ? err.message : String(err) }
    }

    const id = randomUUID()
    const dir = serverDir(id)
    const now = new Date().toISOString()

    const meta: HostServerMeta = {
      id,
      name: input.name.trim(),
      software: input.software,
      mcVersion: input.mcVersion,
      build: build.id,
      ramMb: Math.floor(input.ramMb),
      port: input.port,
      javaPath: input.javaPath ?? null,
      eulaAccepted: Boolean(input.acceptEula),
      jarFileName: JAR_NAME,
      createdAt: now,
      updatedAt: now
    }

    try {
      await mkdir(join(dir, 'plugins'), { recursive: true })
      await mkdir(join(dir, 'logs'), { recursive: true })
      await writeFile(metaPath(id), JSON.stringify(meta, null, 2), 'utf8')
      await writeFile(propertiesPath(id), serializeProperties(defaultProperties(meta.port, meta.name)), 'utf8')
      await writeFile(
        eulaPath(id),
        `#By changing the setting below to TRUE you are indicating your agreement to our EULA (https://aka.ms/MinecraftEULA).\neula=${meta.eulaAccepted ? 'true' : 'false'}\n`,
        'utf8'
      )

      await this.downloadJar(id, build.downloadUrl, build.sha256)
      return { ok: true, server: await this.toView(meta) }
    } catch (err) {
      await rm(dir, { recursive: true, force: true }).catch(() => undefined)
      return { ok: false, error: err instanceof Error ? err.message : String(err) }
    }
  }

  async update(input: UpdateHostServerDto): Promise<HostMutationDto> {
    let meta: HostServerMeta
    try {
      meta = await this.readMeta(input.id)
    } catch {
      return { ok: false, error: 'Server not found.' }
    }

    if (input.name !== undefined) {
      const nameErr = validateName(input.name)
      if (nameErr) return { ok: false, error: nameErr }
      meta.name = input.name.trim()
    }
    if (input.ramMb !== undefined) {
      const ramErr = validateRam(input.ramMb)
      if (ramErr) return { ok: false, error: ramErr }
      meta.ramMb = Math.floor(input.ramMb)
    }
    if (input.port !== undefined) {
      const portErr = validatePort(input.port)
      if (portErr) return { ok: false, error: portErr }
      meta.port = input.port
      await this.patchProperties(input.id, { 'server-port': String(input.port) })
    }
    if (input.javaPath !== undefined) {
      meta.javaPath = input.javaPath
    }

    meta.updatedAt = new Date().toISOString()
    await this.writeMeta(meta)
    return { ok: true, server: await this.toView(meta) }
  }

  async remove(id: string, deleteFiles = true): Promise<HostMutationDto> {
    if (serverProcessManager.isRunning(id)) {
      return { ok: false, error: 'Stop the server before deleting it.' }
    }
    try {
      await this.readMeta(id)
    } catch {
      return { ok: false, error: 'Server not found.' }
    }
    if (deleteFiles) {
      await rm(serverDir(id), { recursive: true, force: true })
    }
    return { ok: true }
  }

  async acceptEula(id: string): Promise<HostMutationDto> {
    let meta: HostServerMeta
    try {
      meta = await this.readMeta(id)
    } catch {
      return { ok: false, error: 'Server not found.' }
    }
    meta.eulaAccepted = true
    meta.updatedAt = new Date().toISOString()
    await writeFile(
      eulaPath(id),
      `#By changing the setting below to TRUE you are indicating your agreement to our EULA (https://aka.ms/MinecraftEULA).\neula=true\n`,
      'utf8'
    )
    await this.writeMeta(meta)
    return { ok: true, server: await this.toView(meta) }
  }

  async getProperties(id: string): Promise<HostPropertiesDto | null> {
    if (!(await pathExists(propertiesPath(id)))) return null
    const rawText = await readFile(propertiesPath(id), 'utf8')
    const raw = parseProperties(rawText)
    const editable: Partial<Record<HostEditablePropertyKey, string>> = {}
    for (const key of HOST_EDITABLE_PROPERTIES) {
      if (raw[key] !== undefined) {
        editable[key] = raw[key]
      }
    }
    return { raw, editable }
  }

  async updateProperties(
    id: string,
    patch: Partial<Record<HostEditablePropertyKey, string>>
  ): Promise<HostMutationDto> {
    try {
      await this.readMeta(id)
    } catch {
      return { ok: false, error: 'Server not found.' }
    }
    if (serverProcessManager.isRunning(id)) {
      return { ok: false, error: 'Stop the server before editing properties.' }
    }

    const cleaned: Partial<Record<HostEditablePropertyKey, string>> = {}
    for (const key of HOST_EDITABLE_PROPERTIES) {
      if (patch[key] !== undefined) {
        cleaned[key] = String(patch[key])
      }
    }

    if (cleaned['server-port']) {
      const port = Number(cleaned['server-port'])
      const portErr = validatePort(port)
      if (portErr) return { ok: false, error: portErr }
    }

    await this.patchProperties(id, cleaned)

    if (cleaned['server-port']) {
      const port = Number(cleaned['server-port'])
      const meta = await this.readMeta(id)
      meta.port = port
      meta.updatedAt = new Date().toISOString()
      await this.writeMeta(meta)
    }

    return { ok: true, server: (await this.get(id)) ?? undefined }
  }

  async start(id: string): Promise<HostMutationDto> {
    let meta: HostServerMeta
    try {
      meta = await this.readMeta(id)
    } catch {
      return { ok: false, error: 'Server not found.' }
    }

    if (!meta.eulaAccepted) {
      return { ok: false, error: 'You must accept the Minecraft EULA before starting the server.' }
    }
    if (!(await pathExists(jarPath(id)))) {
      return { ok: false, error: 'server.jar is missing. Recreate the server or re-download the JAR.' }
    }

    try {
      const settings = await settingsStore.load()
      const javaPath = await resolveJavaPath(meta.javaPath || settings.defaultJavaPath)
      await serverProcessManager.start({
        serverId: id,
        cwd: serverDir(id),
        javaPath,
        jarPath: jarPath(id),
        ramMb: meta.ramMb,
        jvmArgs: settings.jvmArgs
      })
      return { ok: true, server: await this.toView(meta) }
    } catch (err) {
      return { ok: false, error: err instanceof Error ? err.message : String(err) }
    }
  }

  async stop(id: string): Promise<HostMutationDto> {
    try {
      await serverProcessManager.stop(id)
      const server = await this.get(id)
      return { ok: true, server: server ?? undefined }
    } catch (err) {
      return { ok: false, error: err instanceof Error ? err.message : String(err) }
    }
  }

  async restart(id: string): Promise<HostMutationDto> {
    let meta: HostServerMeta
    try {
      meta = await this.readMeta(id)
    } catch {
      return { ok: false, error: 'Server not found.' }
    }
    if (!meta.eulaAccepted) {
      return { ok: false, error: 'You must accept the Minecraft EULA before starting the server.' }
    }

    try {
      const settings = await settingsStore.load()
      const javaPath = await resolveJavaPath(meta.javaPath || settings.defaultJavaPath)
      await serverProcessManager.restart({
        serverId: id,
        cwd: serverDir(id),
        javaPath,
        jarPath: jarPath(id),
        ramMb: meta.ramMb,
        jvmArgs: settings.jvmArgs
      })
      return { ok: true, server: await this.toView(meta) }
    } catch (err) {
      return { ok: false, error: err instanceof Error ? err.message : String(err) }
    }
  }

  sendCommand(id: string, command: string): { ok: boolean; error?: string } {
    try {
      serverProcessManager.sendCommand(id, command)
      return { ok: true }
    } catch (err) {
      return { ok: false, error: err instanceof Error ? err.message : String(err) }
    }
  }

  async openFolder(id: string): Promise<{ ok: boolean; error?: string }> {
    const dir = serverDir(id)
    if (!(await pathExists(dir))) {
      return { ok: false, error: 'Server folder not found.' }
    }
    const result = await shell.openPath(dir)
    return result ? { ok: false, error: result } : { ok: true }
  }

  async listWorlds(id: string): Promise<HostWorldEntryDto[]> {
    const dir = serverDir(id)
    if (!(await pathExists(dir))) return []
    const entries = await readdir(dir, { withFileTypes: true })
    const worlds: HostWorldEntryDto[] = []
    for (const entry of entries) {
      if (!entry.isDirectory()) continue
      const levelDat = join(dir, entry.name, 'level.dat')
      const isLevel = await pathExists(levelDat)
      if (isLevel || entry.name === 'world' || entry.name.startsWith('world_')) {
        worlds.push({
          name: entry.name,
          path: join(dir, entry.name),
          isLevel
        })
      }
    }
    return worlds.sort((a, b) => a.name.localeCompare(b.name))
  }

  getPluginsDir(id: string): string {
    return join(serverDir(id), 'plugins')
  }

  getServerDir(id: string): string {
    return serverDir(id)
  }

  // ── private helpers ──────────────────────────────────────────────

  private async readMeta(id: string): Promise<HostServerMeta> {
    const raw = await readFile(metaPath(id), 'utf8')
    return JSON.parse(raw) as HostServerMeta
  }

  private async writeMeta(meta: HostServerMeta): Promise<void> {
    await writeFile(metaPath(meta.id), JSON.stringify(meta, null, 2), 'utf8')
  }

  private async toView(meta: HostServerMeta): Promise<HostServerView> {
    const jarReady = await pathExists(jarPath(meta.id))
    return {
      ...meta,
      status: serverProcessManager.getStatus(meta.id),
      dir: serverDir(meta.id),
      jarReady
    }
  }

  private async patchProperties(
    id: string,
    patch: Partial<Record<string, string>>
  ): Promise<void> {
    let map: Record<string, string> = {}
    if (await pathExists(propertiesPath(id))) {
      map = parseProperties(await readFile(propertiesPath(id), 'utf8'))
    }
    Object.assign(map, patch)
    await writeFile(propertiesPath(id), serializeProperties(map), 'utf8')
  }

  private async downloadJar(serverId: string, url: string, sha256?: string): Promise<void> {
    broadcastDownload({
      serverId,
      phase: 'start',
      percent: 0,
      detail: 'Starting server JAR download…'
    })
    try {
      await downloadService.downloadFile({
        url,
        destPath: jarPath(serverId),
        sha256,
        headers: { 'User-Agent': 'Prime-Launcher/2.5.0 (Local Server Host)' },
        onProgress: (percent, speed) => {
          broadcastDownload({
            serverId,
            phase: 'download',
            percent,
            detail: `Downloading server.jar…`,
            speed
          })
        }
      })
      // Ensure file exists / has size
      const info = await stat(jarPath(serverId))
      if (info.size < 1024) {
        throw new Error('Downloaded JAR looks empty or corrupt.')
      }
      broadcastDownload({
        serverId,
        phase: 'done',
        percent: 100,
        detail: 'Server JAR ready.'
      })
    } catch (err) {
      const detail = err instanceof Error ? err.message : String(err)
      broadcastDownload({
        serverId,
        phase: 'error',
        percent: 0,
        detail
      })
      throw err
    }
  }
}

export const hostServerService = new HostServerService()
